### ISSUE TITLE
Capturar data e hora para controle de acesso.

### ISSUE THREAD

**Issue by DenisWP** [Host32/Shared-Wifi#25]
Controlar o acesso do cliente, capturando a data e a hora que ele conectou.

**Comment by DenisWP** [comment]
Funções em C desenvolvidas, caso precise. Porém, estamos estudando uma forma de capturar a data e hora do sistema, utilizando diretamente o SQlite3.

**Comment by mailysantos** [comment]
Feito utilizando o sqlite.  Faz parte do commit: https://github.com/Host32/Shared-Wifi/commit/5587cfdf53da4346d19a45fc757ec66424daf73a
